language: generic

before_script:
  - pwd
  - chmod 400 amazon-vm-key.pem
  - scp -i amazon-vm-key.pem -o "StrictHostKeyChecking no" -r /home/travis/build/paksip/docker-ci-test/* ec2-user@ec2-3-15-165-161.us-east-2.compute.amazonaws.com:/home/ec2-user/test_volume

branches:
  only:
    - master