language: generic

before_script:
  - pwd
  - scp -o "StrictHostKeyChecking no" -r -i amazon-vm-key.pem . ec2-user@ec2-3-15-165-161.us-east-2.compute.amazonaws.com:/home/ec2-user/test_volume

branches:
  only:
    - master