language: generic

before_script:
  - pwd
  - chmod 400 amazon-vm-key.pem
  - scp -i amazon-vm-key.pem -o "StrictHostKeyChecking no" -r /home/travis/build/paksip/docker-ci-test/out/* ec2-user@ec2-3-23-132-55.us-east-2.compute.amazonaws.com:/home/ec2-user/volumes/docker-ci-test

branches:
  only:
    - master